# Generated by Django 4.1 on 2023-05-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_index_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='active',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
