# Generated by Django 4.1 on 2023-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_index_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('index_id', models.CharField(max_length=100)),
                ('active', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
