# Generated by Django 4.1 on 2023-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('weburl', models.TextField()),
                ('address', models.TextField()),
                ('purchase_type', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('floor_area', models.CharField(max_length=200)),
                ('Bedroom', models.CharField(max_length=200)),
                ('bathroom', models.CharField(max_length=200)),
                ('features', models.CharField(max_length=200)),
                ('amenties', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('image', models.CharField(default=None, max_length=200, null=True)),
                ('is_admin', models.CharField(max_length=200)),
            ],
        ),
    ]
