# Generated by Django 4.1 on 2023-05-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_prperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='title',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
