# Generated by Django 4.1 on 2023-05-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_prperty_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='user_id',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
