# Generated by Django 4.1 on 2023-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_prperty_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='floor_area_value',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
