# Generated by Django 4.1 on 2023-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_prperty_floor_area_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='amount',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
