# Generated by Django 4.1 on 2023-05-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_propertyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prperty',
            name='image',
            field=models.ImageField(default='default value', upload_to='images/'),
        ),
    ]
