# Generated by Django 4.1 on 2023-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_prperty_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/admin/index/images/'),
        ),
    ]
