# Generated by Django 4.1 on 2023-05-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_index_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/property/images/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/index/images/'),
        ),
    ]
