# Generated by Django 4.1 on 2023-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_category_image_alter_index_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/category/images/'),
        ),
    ]
