# Generated by Django 4.1 on 2023-05-30 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='propertyuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
