# Generated by Django 4.1.1 on 2023-06-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='hide',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='prperty',
            name='site_area',
            field=models.CharField(default='default value', max_length=100),
        ),
        migrations.AddField(
            model_name='prperty',
            name='site_area_value',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
