# Generated by Django 4.1.1 on 2023-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_prperty_hide_prperty_site_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='created_at',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
