# Generated by Django 4.1.1 on 2023-06-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_prperty_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='created_at',
            field=models.CharField(default='default value', max_length=100),
        ),
    ]
