# Generated by Django 4.1.1 on 2023-06-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_prperty_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prperty',
            name='created_at',
        ),
    ]
