# Generated by Django 4.1.1 on 2023-06-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='opt',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
