# Generated by Django 4.1.1 on 2023-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_customuser_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='Continent',
            field=models.CharField(default='default value', max_length=200),
        ),
        migrations.AddField(
            model_name='prperty',
            name='Country',
            field=models.CharField(default='default value', max_length=200),
        ),
    ]
