# Generated by Django 4.1.1 on 2023-06-21 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_prperty_continent_prperty_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='prperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
