# Generated by Django 4.1.1 on 2023-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_prperty_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateField()),
                ('number', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('status_value', models.CharField(max_length=100)),
                ('prop_type', models.CharField(max_length=100)),
                ('features', models.CharField(max_length=100)),
                ('exterior', models.CharField(max_length=100)),
                ('interior', models.CharField(max_length=100)),
                ('energy_efficiency', models.CharField(max_length=100)),
                ('environmental_impact', models.CharField(max_length=100)),
                ('riverside', models.CharField(max_length=100)),
                ('seaside', models.CharField(max_length=100)),
                ('bar', models.CharField(max_length=100)),
                ('convenience_store', models.CharField(max_length=100)),
                ('fire_station', models.CharField(max_length=100)),
                ('gym', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('nursery', models.CharField(max_length=100)),
                ('park', models.CharField(max_length=100)),
                ('petrol_station', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('restaurant', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('super_market', models.CharField(max_length=100)),
                ('floor_area', models.CharField(max_length=100)),
                ('site_area', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('living_room', models.CharField(max_length=100)),
                ('bedroom1', models.CharField(max_length=100)),
                ('bedroom2', models.CharField(max_length=100)),
                ('bedroom3', models.CharField(max_length=100)),
                ('airport', models.CharField(max_length=100)),
                ('bus_stop', models.CharField(max_length=100)),
                ('train_station', models.CharField(max_length=100)),
                ('underground_station', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
