# Generated by Django 4.1.1 on 2023-07-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_database_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='sort',
            field=models.CharField(default='', max_length=200),
        ),
    ]
