# Generated by Django 4.1.1 on 2023-07-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_database_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='action',
            field=models.CharField(default='', max_length=200),
        ),
    ]
