# Generated by Django 4.1.1 on 2023-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_database_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='action',
        ),
        migrations.AlterField(
            model_name='database',
            name='date_added',
            field=models.CharField(max_length=100),
        ),
    ]
