# Generated by Django 4.1.1 on 2023-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_remove_database_action_alter_database_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='date_added',
            field=models.DateField(),
        ),
    ]
