# Generated by Django 4.1.1 on 2023-07-28 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_alter_database_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=100)),
                ('interior', models.CharField(default='', max_length=100)),
                ('exterior', models.CharField(default='', max_length=100)),
                ('property_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(default='', max_length=100)),
                ('date_added', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='property_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
