# Generated by Django 4.1.1 on 2023-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_alter_prperty_continent_alter_prperty_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='date_added',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='database',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
