# Generated by Django 4.1.1 on 2023-08-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_rename_date_added_database_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
