# Generated by Django 4.1.1 on 2023-08-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_alter_database_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
