# Generated by Django 4.2.5 on 2023-09-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_alter_prperty_amenties'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
