# Generated by Django 4.2.5 on 2023-10-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_database_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField()),
                ('exterior', models.IntegerField()),
                ('interior', models.IntegerField()),
                ('energy_efficiency', models.IntegerField()),
                ('environmental_impact', models.IntegerField()),
                ('riverside', models.IntegerField()),
                ('seaside', models.IntegerField()),
                ('bar', models.IntegerField()),
                ('convenience_store', models.IntegerField()),
                ('fire_station', models.IntegerField()),
                ('gym', models.IntegerField()),
                ('hospital', models.IntegerField()),
                ('nursery', models.IntegerField()),
                ('park', models.IntegerField()),
                ('petrol_station', models.IntegerField()),
                ('police_station', models.IntegerField()),
                ('restaurant', models.IntegerField()),
                ('school', models.IntegerField()),
                ('super_market', models.IntegerField()),
                ('floor_area', models.IntegerField()),
                ('site_area', models.IntegerField()),
                ('kitchen', models.IntegerField()),
                ('living_room', models.IntegerField()),
                ('bedroom1', models.IntegerField()),
                ('bedroom2', models.IntegerField()),
                ('bedroom3', models.IntegerField()),
                ('airport', models.IntegerField()),
                ('bus_stop', models.IntegerField()),
                ('train_station', models.IntegerField()),
                ('underground_station', models.IntegerField()),
            ],
        ),
    ]
