# Generated by Django 4.2.5 on 2023-10-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_percentile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percentile',
        ),
    ]
