# Generated by Django 4.2.5 on 2023-10-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Percentile',
        ),
    ]
