# Generated by Django 4.2.5 on 2023-10-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_delete_percentile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100)),
                ('exterior', models.CharField(default='', max_length=100)),
                ('interior', models.CharField(default='', max_length=100)),
                ('energy_efficiency', models.CharField(default='', max_length=100)),
                ('environmental_impact', models.CharField(default='', max_length=100)),
                ('riverside', models.CharField(default='', max_length=100)),
                ('seaside', models.CharField(default='', max_length=100)),
                ('bar', models.CharField(default='', max_length=100)),
                ('convenience_store', models.CharField(default='', max_length=100)),
                ('fire_station', models.CharField(default='', max_length=100)),
                ('gym', models.CharField(default='', max_length=100)),
                ('hospital', models.CharField(default='', max_length=100)),
                ('nursery', models.CharField(default='', max_length=100)),
                ('park', models.CharField(default='', max_length=100)),
                ('petrol_station', models.CharField(default='', max_length=100)),
                ('police_station', models.CharField(default='', max_length=100)),
                ('restaurant', models.CharField(default='', max_length=100)),
                ('school', models.CharField(default='', max_length=100)),
                ('super_market', models.CharField(default='', max_length=100)),
                ('floor_area', models.CharField(default='', max_length=100)),
                ('site_area', models.CharField(default='', max_length=100)),
                ('kitchen', models.CharField(default='', max_length=100)),
                ('living_room', models.CharField(default='', max_length=100)),
                ('bedroom1', models.CharField(default='', max_length=100)),
                ('bedroom2', models.CharField(default='', max_length=100)),
                ('bedroom3', models.CharField(default='', max_length=100)),
                ('airport', models.CharField(default='', max_length=100)),
                ('bus_stop', models.CharField(default='', max_length=100)),
                ('train_station', models.CharField(default='', max_length=100)),
                ('underground_station', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
