# Generated by Django 4.2.5 on 2023-11-07 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_propertypercentile_delete_percentrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypercentile',
            name='Bedroom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='Continent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='Country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='amenties',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='bathroom',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='features',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='hide',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='index',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='is_admin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='property_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='purchase_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='weburl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='airport',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='bar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='bedroom1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='bedroom2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='bedroom3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='bus_stop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='convenience_store',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='energy_efficiency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='environmental_impact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='exterior',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='fire_station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='floor_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='gym',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='hospital',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='interior',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='kitchen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='living_room',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='nursery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='park',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='petrol_station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='police_station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='restaurant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='riverside',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='seaside',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='site_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='super_market',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='train_station',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentile',
            name='underground_station',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
