# Generated by Django 4.2.5 on 2023-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_propertypercentile_bedroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypercentile',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertypercentile',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
