# Generated by Django 4.2.5 on 2023-11-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_propertypercentile_date_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
