# Generated by Django 4.2.5 on 2023-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_database_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='duration',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
