# Generated by Django 4.2.5 on 2023-11-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0053_database_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypercentile',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prperty',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
